In [22]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer ##importing simple imputer function from sllearn
imputer = SimpleImputer(missing_values = np.nan,strategy='mean')

In [23]:
df = pd.read_csv('googleplaystore.csv')  ## loaded the data

In [24]:
df.drop(['Last Updated','Current Ver','Android Ver'],axis = 1,inplace=True)

In [25]:
df_drop=df.dropna()   ##found the null value and dropping th row which is having null value

In [26]:
df_drop #here we have removed some row******more quality data better the accuracy

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10834                                      FR Calculator               FAMILY   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0   
1         3.9     967                 14M     500,000+  Free     0   
2         4.7   87510                8.7M   5,000,000+  Free     0   
3         4.5  215644                 25M  50,000,000+  Free     0   
4         4.3     967                2.8M     100,000+  Free     0   
...       ...     ...                 ...          ...   ...   ...   
10834     4.0       7                2.6M         500+  Free     0   
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres  
0           Everyone               Art & Design  
1           Everyone  Art & Design;Pretend Play  
2           Everyone               Art & Design  
3               Teen               Art & Design  
4           Everyone    Art & Design;Creativity  
...              ...                        ...  
10834       Everyone                  Education  
10836       Everyone                  Education  
10837       Everyone                  Education  
10839     Mature 17+          Books & Reference  
10840       Everyone                  Lifestyle  

[9366 rows x 10 columns]

In [27]:
len(df)-len(df_drop)##1475 all the value has been removed which is having null value

1475

###2 working with **imputers** here we are not removing the value coz more quality data better the accuracy here we will remove the null value with some other value in the datasets now we will see how to fill any value in the place of null by importing sklearn.impute import simpleimper

In [28]:
df

App             Category  \
0         Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   
1                                    Coloring book moana       ART_AND_DESIGN   
2      U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   
3                                  Sketch - Draw & Paint       ART_AND_DESIGN   
4                  Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   
...                                                  ...                  ...   
10836                                   Sya9a Maroc - FR               FAMILY   
10837                   Fr. Mike Schmitz Audio Teachings               FAMILY   
10838                             Parkinson Exercices FR              MEDICAL   
10839                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   
10840      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   

       Rating Reviews                Size     Installs  Type Price  \
0         4.1     159                 19M      10,000+  Free     0   
1         3.9     967                 14M     500,000+  Free     0   
2         4.7   87510                8.7M   5,000,000+  Free     0   
3         4.5  215644                 25M  50,000,000+  Free     0   
4         4.3     967                2.8M     100,000+  Free     0   
...       ...     ...                 ...          ...   ...   ...   
10836     4.5      38                 53M       5,000+  Free     0   
10837     5.0       4                3.6M         100+  Free     0   
10838     NaN       3                9.5M       1,000+  Free     0   
10839     4.5     114  Varies with device       1,000+  Free     0   
10840     4.5  398307                 19M  10,000,000+  Free     0   

      Content Rating                     Genres  
0           Everyone               Art & Design  
1           Everyone  Art & Design;Pretend Play  
2           Everyone               Art & Design  
3               Teen               Art & Design  
4           Everyone    Art & Design;Creativity  
...              ...                        ...  
10836       Everyone                  Education  
10837       Everyone                  Education  
10838       Everyone                    Medical  
10839     Mature 17+          Books & Reference  
10840       Everyone                  Lifestyle  

[10841 rows x 10 columns]

In [29]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
dtype: int64

In [30]:
df['Rating']

0        4.1
1        3.9
2        4.7
3        4.5
4        4.3
        ... 
10836    4.5
10837    5.0
10838    NaN
10839    4.5
10840    4.5
Name: Rating, Length: 10841, dtype: float64

##### here we have numeric data we can deal with them in different ways like we can find mean value and replece the result eith *NAN* AND ...for string we can do other manipulation

In [31]:
min(df['Rating']) ##minimum value index

1.0

In [32]:
max(df['Rating']) #maximum value index

19.0

In [33]:
##example to insert
lst = [4.1, 3.1,1.4,4.5,5.6,2.1,4.4,1.5] ## missing one value
#lst = [4.1,4.0,3.1,1.4,4.5,5.6,2.1,4.4,1.5] ## original list

In [34]:

sump = 0.0

for i in lst:
    sump += i
    
print(sump)    

26.700000000000003


In [35]:
sum(lst)

26.700000000000003

In [36]:
len(lst)

8

In [37]:
sump = 0.0

for i in lst:
    sump += i
    
print(sump/8)  ## on finding average we are getting 3.33   it should be placed inthe place of null vaklue of datasets

3.3375000000000004


In [38]:
#2nd way we will find mode for the list value,means we will be geeting which rating is occuring most of the time
lst = [4.1,4.0,4.0,4.0,    4.5,5.0,4.1,4.4,4.5,3.4]#4.0 occusrs three times whichis the maximum we can replace it will NAN VALUE

####here i just need to deal with rating ,i take this df of rating and this rating i will pass through the imputers "imputer = SimpleImputer()"

In [39]:
imputer.fit(df['Rating']) ## printing this will give error.... convert it into numpy array first

ValueError: Expected 2D array, got 1D array instead:
array=[4.1 3.9 4.7 ... nan 4.5 4.5].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [40]:
#use indexing
df['Rating'].values ##we cannot pass directly we need to reshape it as well passing it to the imputer fun is showing to reshape the data

array([4.1, 3.9, 4.7, ..., nan, 4.5, 4.5])

In [41]:
df['Rating'].values.shape # to reshape we need to shape first

(10841,)

In [42]:
#i need to reshape it into (-1,1)
rating = np.reshape(df['Rating'].values,  (10841,1))

In [44]:
imputer.fit(rating)  #fitting 

SimpleImputer()

In [46]:
rating[:50]

array([[4.1],
       [3.9],
       [4.7],
       [4.5],
       [4.3],
       [4.4],
       [3.8],
       [4.1],
       [4.4],
       [4.7],
       [4.4],
       [4.4],
       [4.2],
       [4.6],
       [4.4],
       [3.2],
       [4.7],
       [4.5],
       [4.3],
       [4.6],
       [4. ],
       [4.1],
       [4.7],
       [nan],
       [4.7],
       [4.8],
       [4.7],
       [4.1],
       [3.9],
       [4.1],
       [4.2],
       [4.1],
       [4.5],
       [4.2],
       [4.7],
       [3.8],
       [4.7],
       [4.1],
       [4.7],
       [4. ],
       [4.2],
       [4.5],
       [4.4],
       [3.8],
       [4.2],
       [4.7],
       [4.6],
       [4.2],
       [4.3],
       [4.2]])

In [49]:
rating

array([[4.1],
       [3.9],
       [4.7],
       ...,
       [nan],
       [4.5],
       [4.5]])

In [47]:
imputer.transform(rating) #earlier we are having null value by using tarnsform we got a value at the place of null value

array([[4.1       ],
       [3.9       ],
       [4.7       ],
       ...,
       [4.19333832],
       [4.5       ],
       [4.5       ]])

In [51]:
#but the rating is not in original format
df.iloc[ : , 2: 3] =imputer.transform(rating) #convert the whole row and one column for category into dataframe  

In [53]:
df.head(10) ## the " nan " value is replaced with some particular value

App        Category  Rating  \
0     Photo Editor & Candy Camera & Grid & ScrapBook  ART_AND_DESIGN     4.1   
1                                Coloring book moana  ART_AND_DESIGN     3.9   
2  U Launcher Lite – FREE Live Cool Themes, Hide ...  ART_AND_DESIGN     4.7   
3                              Sketch - Draw & Paint  ART_AND_DESIGN     4.5   
4              Pixel Draw - Number Art Coloring Book  ART_AND_DESIGN     4.3   
5                         Paper flowers instructions  ART_AND_DESIGN     4.4   
6            Smoke Effect Photo Maker - Smoke Editor  ART_AND_DESIGN     3.8   
7                                   Infinite Painter  ART_AND_DESIGN     4.1   
8                               Garden Coloring Book  ART_AND_DESIGN     4.4   
9                      Kids Paint Free - Drawing Fun  ART_AND_DESIGN     4.7   

  Reviews  Size     Installs  Type Price Content Rating  \
0     159   19M      10,000+  Free     0       Everyone   
1     967   14M     500,000+  Free     0       Everyone   
2   87510  8.7M   5,000,000+  Free     0       Everyone   
3  215644   25M  50,000,000+  Free     0           Teen   
4     967  2.8M     100,000+  Free     0       Everyone   
5     167  5.6M      50,000+  Free     0       Everyone   
6     178   19M      50,000+  Free     0       Everyone   
7   36815   29M   1,000,000+  Free     0       Everyone   
8   13791   33M   1,000,000+  Free     0       Everyone   
9     121  3.1M      10,000+  Free     0       Everyone   

                      Genres  
0               Art & Design  
1  Art & Design;Pretend Play  
2               Art & Design  
3               Art & Design  
4    Art & Design;Creativity  
5               Art & Design  
6               Art & Design  
7               Art & Design  
8               Art & Design  
9    Art & Design;Creativity

In [54]:
df.isnull()

App  Category  Rating  Reviews   Size  Installs   Type  Price  \
0      False     False   False    False  False     False  False  False   
1      False     False   False    False  False     False  False  False   
2      False     False   False    False  False     False  False  False   
3      False     False   False    False  False     False  False  False   
4      False     False   False    False  False     False  False  False   
...      ...       ...     ...      ...    ...       ...    ...    ...   
10836  False     False   False    False  False     False  False  False   
10837  False     False   False    False  False     False  False  False   
10838  False     False   False    False  False     False  False  False   
10839  False     False   False    False  False     False  False  False   
10840  False     False   False    False  False     False  False  False   

       Content Rating  Genres  
0               False   False  
1               False   False  
2               False   False  
3               False   False  
4               False   False  
...               ...     ...  
10836           False   False  
10837           False   False  
10838           False   False  
10839           False   False  
10840           False   False  

[10841 rows x 10 columns]

In [56]:
df.isnull().sum()  #now category rating have no null value

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              1
Price             0
Content Rating    1
Genres            0
dtype: int64