In [9]:
import numpy as np

In [10]:
numpy

<module 'numpy' from 'C:\\anaconda12\\lib\\site-packages\\numpy\\__init__.py'>

In [17]:
lst=[[1,2,3,9],[4,5,6,0],[7,8,9,2]]
type(lst)

list

In [18]:
np_array=np.array(lst)

In [19]:
np_array

array([[1, 2, 3, 9],
       [4, 5, 6, 0],
       [7, 8, 9, 2]])

In [20]:
np_array.shape

(3, 4)

In [21]:
np_array=np.reshape(np_array,(4,3))

In [22]:
np_array

array([[1, 2, 3],
       [9, 4, 5],
       [6, 0, 7],
       [8, 9, 2]])

In [24]:
np_array.shape

(4, 3)

In [25]:
np.zeros((4,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
np.ones((13,8), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
## rrandom no generator

In [34]:
rand=np.random.randint(0,9)
print(rand)

3


In [35]:
 np.linspace(2,10,7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [36]:
np.mean(np.linspace(2,10,7))

6.0

In [37]:
np.sqrt(np.linspace(2,10,7))

array([1.41421356, 1.82574186, 2.1602469 , 2.44948974, 2.7080128 ,
       2.94392029, 3.16227766])

In [38]:
array=np.linspace(2,10,7)

In [39]:
array

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [40]:
array+4

array([ 6.        ,  7.33333333,  8.66666667, 10.        , 11.33333333,
       12.66666667, 14.        ])

In [41]:
array-2

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [42]:
array*3

array([ 6., 10., 14., 18., 22., 26., 30.])

In [43]:
array/2

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])